   0.0 TEL | Telepresence 0.101 launched at Thu Mar 19 19:00:19 2020
   0.0 TEL |   /usr/local/bin/telepresence --namespace 5d964b94de40b40012a28041 --swap-deployment actions --expose 5055
   0.0 TEL | Platform: darwin
   0.0 TEL | Python 3.7.4 (default, Oct 12 2019, 18:55:28)
   0.0 TEL | [Clang 11.0.0 (clang-1100.0.33.8)]
   0.0 TEL | [1] Running: uname -a
   0.0   1 | Darwin adrianmac.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
   0.0 TEL | [1] ran in 0.01 secs.
   0.0 TEL | BEGIN SPAN main.py:40(main)
   0.0 TEL | BEGIN SPAN startup.py:74(__init__)
   0.0 TEL | Found kubectl -> /usr/local/bin/kubectl
   0.0 TEL | [2] Capturing: kubectl version --short
  30.5   2 | Unable to connect to the server: dial tcp 34.83.207.0:443: i/o timeout
  30.5 TEL | [2] exit 1 in 30.45 secs.
  30.5 TEL | [3] Capturing: kubectl config current-context
  30.6 TEL | [3] captured in 0.11 secs.
  30.6 TEL | [4] Capturing: kubectl config view -o json
  30.7 TEL | [4] captured in 0.10 secs.
  30.7 TEL | [5] Capturing: kubectl --context gke_edifius-main_us-west1_us-west1-multitenant-edifius get ns 5d964b94de40b40012a28041
  30.8   5 | Unable to connect to the server: dial tcp 34.83.207.0:443: connect: network is unreachable
  30.8 TEL | [5] exit 1 in 0.10 secs.
  30.8 >>> | 
  30.8 >>> | Error: Namespace '5d964b94de40b40012a28041' does not exist
  30.8 >>> | 
  30.8 TEL | EXITING with status code 255
